name: S3 Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]    # main 브랜치에서 push, pull_request 이벤트가 일어났을 때 실행

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Upload /build to S3
        env:
          BUCKET_NAME: ${{secrets.AWS_S3_BUCKET_NAME}}
        run: |
          aws s3 cp --recursive --region ap-northeast-2 build s3://$BUCKET_NAME
